name: Sphinx

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
    - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pydata-sphinx-theme
    - uses: actions/checkout@v2
    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        build-command: "sphinx-build -b html . build"
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ARU-${{ github.sha }}
        path: docs/build/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/
