name: Sphinx

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
    - name: Install dependencies
      run: |
        pacman-key --init
        pacman -Syu --noconfirm
        pacman -S --noconfirm python
        git clone https://aur.archlinux.org/python-pydata-sphinx-theme.git
        cd python-pydata-sphinx-theme
        makepkg -sric --noconfirm
    - uses: actions/checkout@v2
    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        build-command: "sphinx-build -b html . build"
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ARU-${{ github.sha }}
        path: docs/build/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/
